-- Apply before deploying the comment RPC consumer. The source business
-- transaction refuses to commit if this table is unavailable.
CREATE TABLE IF NOT EXISTS comment_domain_fact_outbox (
    event_id varchar(128) PRIMARY KEY,
    event_type varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Existing deployments may have created comment_like manually. Fresh
-- deployments use the same GORM model through InitDB's AutoMigrate.
CREATE TABLE IF NOT EXISTS comment_like (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    comment_id bigint NOT NULL,
    target_type varchar(32) NOT NULL,
    target_id varchar(64) NOT NULL,
    state integer NOT NULL DEFAULT 0,
    created_at timestamptz,
    updated_at timestamptz,
    CONSTRAINT idx_user_comment_like UNIQUE (user_id, comment_id)
);
