// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: favorite.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FavoriteService_CreateFavoriteFolder_FullMethodName     = "/favorite.FavoriteService/CreateFavoriteFolder"
	FavoriteService_CreateFavorite_FullMethodName           = "/favorite.FavoriteService/CreateFavorite"
	FavoriteService_DeleteFavoriteFolder_FullMethodName     = "/favorite.FavoriteService/DeleteFavoriteFolder"
	FavoriteService_DeleteFavorite_FullMethodName           = "/favorite.FavoriteService/DeleteFavorite"
	FavoriteService_UpdateFavoriteFolderName_FullMethodName = "/favorite.FavoriteService/UpdateFavoriteFolderName"
	FavoriteService_GetFavoriteFolders_FullMethodName       = "/favorite.FavoriteService/GetFavoriteFolders"
	FavoriteService_GetFavoritesByFolder_FullMethodName     = "/favorite.FavoriteService/GetFavoritesByFolder"
)

// FavoriteServiceClient is the client API for FavoriteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteServiceClient interface {
	CreateFavoriteFolder(ctx context.Context, in *CreateFavoriteFolderReq, opts ...grpc.CallOption) (*CreateFavoriteFolderResp, error)
	CreateFavorite(ctx context.Context, in *CreateFavoriteReq, opts ...grpc.CallOption) (*CreateFavoriteResp, error)
	DeleteFavoriteFolder(ctx context.Context, in *DeleteFavoriteFolderReq, opts ...grpc.CallOption) (*DeleteFavoriteFolderResp, error)
	DeleteFavorite(ctx context.Context, in *DeleteFavoriteReq, opts ...grpc.CallOption) (*DeleteFavoriteResp, error)
	UpdateFavoriteFolderName(ctx context.Context, in *UpdateFavoriteFolderNameReq, opts ...grpc.CallOption) (*UpdateFavoriteFolderNameResp, error)
	GetFavoriteFolders(ctx context.Context, in *GetFavoriteFoldersReq, opts ...grpc.CallOption) (*GetFavoriteFoldersResp, error)
	GetFavoritesByFolder(ctx context.Context, in *GetFavoritesByFolderReq, opts ...grpc.CallOption) (*GetFavoritesByFolderResp, error)
}

type favoriteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteServiceClient(cc grpc.ClientConnInterface) FavoriteServiceClient {
	return &favoriteServiceClient{cc}
}

func (c *favoriteServiceClient) CreateFavoriteFolder(ctx context.Context, in *CreateFavoriteFolderReq, opts ...grpc.CallOption) (*CreateFavoriteFolderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFavoriteFolderResp)
	err := c.cc.Invoke(ctx, FavoriteService_CreateFavoriteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) CreateFavorite(ctx context.Context, in *CreateFavoriteReq, opts ...grpc.CallOption) (*CreateFavoriteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFavoriteResp)
	err := c.cc.Invoke(ctx, FavoriteService_CreateFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) DeleteFavoriteFolder(ctx context.Context, in *DeleteFavoriteFolderReq, opts ...grpc.CallOption) (*DeleteFavoriteFolderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavoriteFolderResp)
	err := c.cc.Invoke(ctx, FavoriteService_DeleteFavoriteFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) DeleteFavorite(ctx context.Context, in *DeleteFavoriteReq, opts ...grpc.CallOption) (*DeleteFavoriteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavoriteResp)
	err := c.cc.Invoke(ctx, FavoriteService_DeleteFavorite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) UpdateFavoriteFolderName(ctx context.Context, in *UpdateFavoriteFolderNameReq, opts ...grpc.CallOption) (*UpdateFavoriteFolderNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFavoriteFolderNameResp)
	err := c.cc.Invoke(ctx, FavoriteService_UpdateFavoriteFolderName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) GetFavoriteFolders(ctx context.Context, in *GetFavoriteFoldersReq, opts ...grpc.CallOption) (*GetFavoriteFoldersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoriteFoldersResp)
	err := c.cc.Invoke(ctx, FavoriteService_GetFavoriteFolders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteServiceClient) GetFavoritesByFolder(ctx context.Context, in *GetFavoritesByFolderReq, opts ...grpc.CallOption) (*GetFavoritesByFolderResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavoritesByFolderResp)
	err := c.cc.Invoke(ctx, FavoriteService_GetFavoritesByFolder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavoriteServiceServer is the server API for FavoriteService service.
// All implementations must embed UnimplementedFavoriteServiceServer
// for forward compatibility.
type FavoriteServiceServer interface {
	CreateFavoriteFolder(context.Context, *CreateFavoriteFolderReq) (*CreateFavoriteFolderResp, error)
	CreateFavorite(context.Context, *CreateFavoriteReq) (*CreateFavoriteResp, error)
	DeleteFavoriteFolder(context.Context, *DeleteFavoriteFolderReq) (*DeleteFavoriteFolderResp, error)
	DeleteFavorite(context.Context, *DeleteFavoriteReq) (*DeleteFavoriteResp, error)
	UpdateFavoriteFolderName(context.Context, *UpdateFavoriteFolderNameReq) (*UpdateFavoriteFolderNameResp, error)
	GetFavoriteFolders(context.Context, *GetFavoriteFoldersReq) (*GetFavoriteFoldersResp, error)
	GetFavoritesByFolder(context.Context, *GetFavoritesByFolderReq) (*GetFavoritesByFolderResp, error)
	mustEmbedUnimplementedFavoriteServiceServer()
}

// UnimplementedFavoriteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFavoriteServiceServer struct{}

func (UnimplementedFavoriteServiceServer) CreateFavoriteFolder(context.Context, *CreateFavoriteFolderReq) (*CreateFavoriteFolderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFavoriteFolder not implemented")
}
func (UnimplementedFavoriteServiceServer) CreateFavorite(context.Context, *CreateFavoriteReq) (*CreateFavoriteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFavorite not implemented")
}
func (UnimplementedFavoriteServiceServer) DeleteFavoriteFolder(context.Context, *DeleteFavoriteFolderReq) (*DeleteFavoriteFolderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFavoriteFolder not implemented")
}
func (UnimplementedFavoriteServiceServer) DeleteFavorite(context.Context, *DeleteFavoriteReq) (*DeleteFavoriteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFavorite not implemented")
}
func (UnimplementedFavoriteServiceServer) UpdateFavoriteFolderName(context.Context, *UpdateFavoriteFolderNameReq) (*UpdateFavoriteFolderNameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFavoriteFolderName not implemented")
}
func (UnimplementedFavoriteServiceServer) GetFavoriteFolders(context.Context, *GetFavoriteFoldersReq) (*GetFavoriteFoldersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoriteFolders not implemented")
}
func (UnimplementedFavoriteServiceServer) GetFavoritesByFolder(context.Context, *GetFavoritesByFolderReq) (*GetFavoritesByFolderResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFavoritesByFolder not implemented")
}
func (UnimplementedFavoriteServiceServer) mustEmbedUnimplementedFavoriteServiceServer() {}
func (UnimplementedFavoriteServiceServer) testEmbeddedByValue()                         {}

// UnsafeFavoriteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteServiceServer will
// result in compilation errors.
type UnsafeFavoriteServiceServer interface {
	mustEmbedUnimplementedFavoriteServiceServer()
}

func RegisterFavoriteServiceServer(s grpc.ServiceRegistrar, srv FavoriteServiceServer) {
	// If the following call panics, it indicates UnimplementedFavoriteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FavoriteService_ServiceDesc, srv)
}

func _FavoriteService_CreateFavoriteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFavoriteFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).CreateFavoriteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_CreateFavoriteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).CreateFavoriteFolder(ctx, req.(*CreateFavoriteFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_CreateFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).CreateFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_CreateFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).CreateFavorite(ctx, req.(*CreateFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_DeleteFavoriteFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavoriteFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).DeleteFavoriteFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_DeleteFavoriteFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).DeleteFavoriteFolder(ctx, req.(*DeleteFavoriteFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_DeleteFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavoriteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).DeleteFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_DeleteFavorite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).DeleteFavorite(ctx, req.(*DeleteFavoriteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_UpdateFavoriteFolderName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFavoriteFolderNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).UpdateFavoriteFolderName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_UpdateFavoriteFolderName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).UpdateFavoriteFolderName(ctx, req.(*UpdateFavoriteFolderNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_GetFavoriteFolders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoriteFoldersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).GetFavoriteFolders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_GetFavoriteFolders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).GetFavoriteFolders(ctx, req.(*GetFavoriteFoldersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavoriteService_GetFavoritesByFolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavoritesByFolderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServiceServer).GetFavoritesByFolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavoriteService_GetFavoritesByFolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServiceServer).GetFavoritesByFolder(ctx, req.(*GetFavoritesByFolderReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FavoriteService_ServiceDesc is the grpc.ServiceDesc for FavoriteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavoriteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favorite.FavoriteService",
	HandlerType: (*FavoriteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFavoriteFolder",
			Handler:    _FavoriteService_CreateFavoriteFolder_Handler,
		},
		{
			MethodName: "CreateFavorite",
			Handler:    _FavoriteService_CreateFavorite_Handler,
		},
		{
			MethodName: "DeleteFavoriteFolder",
			Handler:    _FavoriteService_DeleteFavoriteFolder_Handler,
		},
		{
			MethodName: "DeleteFavorite",
			Handler:    _FavoriteService_DeleteFavorite_Handler,
		},
		{
			MethodName: "UpdateFavoriteFolderName",
			Handler:    _FavoriteService_UpdateFavoriteFolderName_Handler,
		},
		{
			MethodName: "GetFavoriteFolders",
			Handler:    _FavoriteService_GetFavoriteFolders_Handler,
		},
		{
			MethodName: "GetFavoritesByFolder",
			Handler:    _FavoriteService_GetFavoritesByFolder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "favorite.proto",
}
