// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: favorite.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteFolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int64                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteFolder) Reset() {
	*x = FavoriteFolder{}
	mi := &file_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteFolder) ProtoMessage() {}

func (x *FavoriteFolder) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteFolder.ProtoReflect.Descriptor instead.
func (*FavoriteFolder) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteFolder) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *FavoriteFolder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteFolder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FavoriteFolder) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FavoriteFolder) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type FavoriteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FavoriteId    int64                  `protobuf:"varint,1,opt,name=favorite_id,json=favoriteId,proto3" json:"favorite_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`       // 被收藏对象ID，比如文章ID
	TargetType    string                 `protobuf:"bytes,5,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 被收藏对象类型，比如 article / post / video
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`                             // 冗余展示字段，可选
	Cover         string                 `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`                             // 冗余展示字段，可选
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteItem) Reset() {
	*x = FavoriteItem{}
	mi := &file_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteItem) ProtoMessage() {}

func (x *FavoriteItem) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteItem.ProtoReflect.Descriptor instead.
func (*FavoriteItem) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteItem) GetFavoriteId() int64 {
	if x != nil {
		return x.FavoriteId
	}
	return 0
}

func (x *FavoriteItem) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *FavoriteItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteItem) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *FavoriteItem) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *FavoriteItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FavoriteItem) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *FavoriteItem) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ************* 1. 新增收藏夹 *************
type CreateFavoriteFolderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFavoriteFolderReq) Reset() {
	*x = CreateFavoriteFolderReq{}
	mi := &file_favorite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFavoriteFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavoriteFolderReq) ProtoMessage() {}

func (x *CreateFavoriteFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavoriteFolderReq.ProtoReflect.Descriptor instead.
func (*CreateFavoriteFolderReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFavoriteFolderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFavoriteFolderReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFavoriteFolderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int64                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFavoriteFolderResp) Reset() {
	*x = CreateFavoriteFolderResp{}
	mi := &file_favorite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFavoriteFolderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavoriteFolderResp) ProtoMessage() {}

func (x *CreateFavoriteFolderResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavoriteFolderResp.ProtoReflect.Descriptor instead.
func (*CreateFavoriteFolderResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFavoriteFolderResp) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

// ************* 2. 新增收藏 *************
type CreateFavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFavoriteReq) Reset() {
	*x = CreateFavoriteReq{}
	mi := &file_favorite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavoriteReq) ProtoMessage() {}

func (x *CreateFavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavoriteReq.ProtoReflect.Descriptor instead.
func (*CreateFavoriteReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{4}
}

func (x *CreateFavoriteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateFavoriteReq) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *CreateFavoriteReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CreateFavoriteReq) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CreateFavoriteReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateFavoriteReq) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

type CreateFavoriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FavoriteId    int64                  `protobuf:"varint,1,opt,name=favorite_id,json=favoriteId,proto3" json:"favorite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFavoriteResp) Reset() {
	*x = CreateFavoriteResp{}
	mi := &file_favorite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFavoriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFavoriteResp) ProtoMessage() {}

func (x *CreateFavoriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFavoriteResp.ProtoReflect.Descriptor instead.
func (*CreateFavoriteResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{5}
}

func (x *CreateFavoriteResp) GetFavoriteId() int64 {
	if x != nil {
		return x.FavoriteId
	}
	return 0
}

// ************* 3. 删除收藏夹 *************
type DeleteFavoriteFolderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavoriteFolderReq) Reset() {
	*x = DeleteFavoriteFolderReq{}
	mi := &file_favorite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavoriteFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavoriteFolderReq) ProtoMessage() {}

func (x *DeleteFavoriteFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavoriteFolderReq.ProtoReflect.Descriptor instead.
func (*DeleteFavoriteFolderReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFavoriteFolderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFavoriteFolderReq) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type DeleteFavoriteFolderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavoriteFolderResp) Reset() {
	*x = DeleteFavoriteFolderResp{}
	mi := &file_favorite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavoriteFolderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavoriteFolderResp) ProtoMessage() {}

func (x *DeleteFavoriteFolderResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavoriteFolderResp.ProtoReflect.Descriptor instead.
func (*DeleteFavoriteFolderResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteFavoriteFolderResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ************* 4. 删除收藏 *************
type DeleteFavoriteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FavoriteId    int64                  `protobuf:"varint,2,opt,name=favorite_id,json=favoriteId,proto3" json:"favorite_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavoriteReq) Reset() {
	*x = DeleteFavoriteReq{}
	mi := &file_favorite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavoriteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavoriteReq) ProtoMessage() {}

func (x *DeleteFavoriteReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavoriteReq.ProtoReflect.Descriptor instead.
func (*DeleteFavoriteReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteFavoriteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFavoriteReq) GetFavoriteId() int64 {
	if x != nil {
		return x.FavoriteId
	}
	return 0
}

type DeleteFavoriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavoriteResp) Reset() {
	*x = DeleteFavoriteResp{}
	mi := &file_favorite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavoriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavoriteResp) ProtoMessage() {}

func (x *DeleteFavoriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavoriteResp.ProtoReflect.Descriptor instead.
func (*DeleteFavoriteResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFavoriteResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ************* 5. 修改收藏夹名字 *************
type UpdateFavoriteFolderNameReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFavoriteFolderNameReq) Reset() {
	*x = UpdateFavoriteFolderNameReq{}
	mi := &file_favorite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFavoriteFolderNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFavoriteFolderNameReq) ProtoMessage() {}

func (x *UpdateFavoriteFolderNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFavoriteFolderNameReq.ProtoReflect.Descriptor instead.
func (*UpdateFavoriteFolderNameReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateFavoriteFolderNameReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateFavoriteFolderNameReq) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *UpdateFavoriteFolderNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateFavoriteFolderNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFavoriteFolderNameResp) Reset() {
	*x = UpdateFavoriteFolderNameResp{}
	mi := &file_favorite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFavoriteFolderNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFavoriteFolderNameResp) ProtoMessage() {}

func (x *UpdateFavoriteFolderNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFavoriteFolderNameResp.ProtoReflect.Descriptor instead.
func (*UpdateFavoriteFolderNameResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateFavoriteFolderNameResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ************* 6. 查询收藏夹 *************
type GetFavoriteFoldersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoriteFoldersReq) Reset() {
	*x = GetFavoriteFoldersReq{}
	mi := &file_favorite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoriteFoldersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteFoldersReq) ProtoMessage() {}

func (x *GetFavoriteFoldersReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteFoldersReq.ProtoReflect.Descriptor instead.
func (*GetFavoriteFoldersReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{12}
}

func (x *GetFavoriteFoldersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFavoriteFoldersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*FavoriteFolder      `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoriteFoldersResp) Reset() {
	*x = GetFavoriteFoldersResp{}
	mi := &file_favorite_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoriteFoldersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoriteFoldersResp) ProtoMessage() {}

func (x *GetFavoriteFoldersResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoriteFoldersResp.ProtoReflect.Descriptor instead.
func (*GetFavoriteFoldersResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{13}
}

func (x *GetFavoriteFoldersResp) GetFolders() []*FavoriteFolder {
	if x != nil {
		return x.Folders
	}
	return nil
}

// ************* 7. 查询收藏夹下的收藏 *************
type GetFavoritesByFolderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolderId      int64                  `protobuf:"varint,2,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesByFolderReq) Reset() {
	*x = GetFavoritesByFolderReq{}
	mi := &file_favorite_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesByFolderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesByFolderReq) ProtoMessage() {}

func (x *GetFavoritesByFolderReq) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesByFolderReq.ProtoReflect.Descriptor instead.
func (*GetFavoritesByFolderReq) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{14}
}

func (x *GetFavoritesByFolderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFavoritesByFolderReq) GetFolderId() int64 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type GetFavoritesByFolderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Favorites     []*FavoriteItem        `protobuf:"bytes,1,rep,name=favorites,proto3" json:"favorites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavoritesByFolderResp) Reset() {
	*x = GetFavoritesByFolderResp{}
	mi := &file_favorite_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavoritesByFolderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavoritesByFolderResp) ProtoMessage() {}

func (x *GetFavoritesByFolderResp) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavoritesByFolderResp.ProtoReflect.Descriptor instead.
func (*GetFavoritesByFolderResp) Descriptor() ([]byte, []int) {
	return file_favorite_proto_rawDescGZIP(), []int{15}
}

func (x *GetFavoritesByFolderResp) GetFavorites() []*FavoriteItem {
	if x != nil {
		return x.Favorites
	}
	return nil
}

var File_favorite_proto protoreflect.FileDescriptor

const file_favorite_proto_rawDesc = "" +
	"\n" +
	"\x0efavorite.proto\x12\bfavorite\"\x98\x01\n" +
	"\x0eFavoriteFolder\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x03R\bfolderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\"\xee\x01\n" +
	"\fFavoriteItem\x12\x1f\n" +
	"\vfavorite_id\x18\x01 \x01(\x03R\n" +
	"favoriteId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x05 \x01(\tR\n" +
	"targetType\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"F\n" +
	"\x17CreateFavoriteFolderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"7\n" +
	"\x18CreateFavoriteFolderResp\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x03R\bfolderId\"\xb3\x01\n" +
	"\x11CreateFavoriteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x04 \x01(\tR\n" +
	"targetType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x06 \x01(\tR\x05cover\"5\n" +
	"\x12CreateFavoriteResp\x12\x1f\n" +
	"\vfavorite_id\x18\x01 \x01(\x03R\n" +
	"favoriteId\"O\n" +
	"\x17DeleteFavoriteFolderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\"4\n" +
	"\x18DeleteFavoriteFolderResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x11DeleteFavoriteReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vfavorite_id\x18\x02 \x01(\x03R\n" +
	"favoriteId\".\n" +
	"\x12DeleteFavoriteResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"g\n" +
	"\x1bUpdateFavoriteFolderNameReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"8\n" +
	"\x1cUpdateFavoriteFolderNameResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetFavoriteFoldersReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"L\n" +
	"\x16GetFavoriteFoldersResp\x122\n" +
	"\afolders\x18\x01 \x03(\v2\x18.favorite.FavoriteFolderR\afolders\"O\n" +
	"\x17GetFavoritesByFolderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfolder_id\x18\x02 \x01(\x03R\bfolderId\"P\n" +
	"\x18GetFavoritesByFolderResp\x124\n" +
	"\tfavorites\x18\x01 \x03(\v2\x16.favorite.FavoriteItemR\tfavorites2\x8c\x05\n" +
	"\x0fFavoriteService\x12]\n" +
	"\x14CreateFavoriteFolder\x12!.favorite.CreateFavoriteFolderReq\x1a\".favorite.CreateFavoriteFolderResp\x12K\n" +
	"\x0eCreateFavorite\x12\x1b.favorite.CreateFavoriteReq\x1a\x1c.favorite.CreateFavoriteResp\x12]\n" +
	"\x14DeleteFavoriteFolder\x12!.favorite.DeleteFavoriteFolderReq\x1a\".favorite.DeleteFavoriteFolderResp\x12K\n" +
	"\x0eDeleteFavorite\x12\x1b.favorite.DeleteFavoriteReq\x1a\x1c.favorite.DeleteFavoriteResp\x12i\n" +
	"\x18UpdateFavoriteFolderName\x12%.favorite.UpdateFavoriteFolderNameReq\x1a&.favorite.UpdateFavoriteFolderNameResp\x12W\n" +
	"\x12GetFavoriteFolders\x12\x1f.favorite.GetFavoriteFoldersReq\x1a .favorite.GetFavoriteFoldersResp\x12]\n" +
	"\x14GetFavoritesByFolder\x12!.favorite.GetFavoritesByFolderReq\x1a\".favorite.GetFavoritesByFolderRespB\x03Z\x01.b\x06proto3"

var (
	file_favorite_proto_rawDescOnce sync.Once
	file_favorite_proto_rawDescData []byte
)

func file_favorite_proto_rawDescGZIP() []byte {
	file_favorite_proto_rawDescOnce.Do(func() {
		file_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_favorite_proto_rawDesc), len(file_favorite_proto_rawDesc)))
	})
	return file_favorite_proto_rawDescData
}

var file_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_favorite_proto_goTypes = []any{
	(*FavoriteFolder)(nil),               // 0: favorite.FavoriteFolder
	(*FavoriteItem)(nil),                 // 1: favorite.FavoriteItem
	(*CreateFavoriteFolderReq)(nil),      // 2: favorite.CreateFavoriteFolderReq
	(*CreateFavoriteFolderResp)(nil),     // 3: favorite.CreateFavoriteFolderResp
	(*CreateFavoriteReq)(nil),            // 4: favorite.CreateFavoriteReq
	(*CreateFavoriteResp)(nil),           // 5: favorite.CreateFavoriteResp
	(*DeleteFavoriteFolderReq)(nil),      // 6: favorite.DeleteFavoriteFolderReq
	(*DeleteFavoriteFolderResp)(nil),     // 7: favorite.DeleteFavoriteFolderResp
	(*DeleteFavoriteReq)(nil),            // 8: favorite.DeleteFavoriteReq
	(*DeleteFavoriteResp)(nil),           // 9: favorite.DeleteFavoriteResp
	(*UpdateFavoriteFolderNameReq)(nil),  // 10: favorite.UpdateFavoriteFolderNameReq
	(*UpdateFavoriteFolderNameResp)(nil), // 11: favorite.UpdateFavoriteFolderNameResp
	(*GetFavoriteFoldersReq)(nil),        // 12: favorite.GetFavoriteFoldersReq
	(*GetFavoriteFoldersResp)(nil),       // 13: favorite.GetFavoriteFoldersResp
	(*GetFavoritesByFolderReq)(nil),      // 14: favorite.GetFavoritesByFolderReq
	(*GetFavoritesByFolderResp)(nil),     // 15: favorite.GetFavoritesByFolderResp
}
var file_favorite_proto_depIdxs = []int32{
	0,  // 0: favorite.GetFavoriteFoldersResp.folders:type_name -> favorite.FavoriteFolder
	1,  // 1: favorite.GetFavoritesByFolderResp.favorites:type_name -> favorite.FavoriteItem
	2,  // 2: favorite.FavoriteService.CreateFavoriteFolder:input_type -> favorite.CreateFavoriteFolderReq
	4,  // 3: favorite.FavoriteService.CreateFavorite:input_type -> favorite.CreateFavoriteReq
	6,  // 4: favorite.FavoriteService.DeleteFavoriteFolder:input_type -> favorite.DeleteFavoriteFolderReq
	8,  // 5: favorite.FavoriteService.DeleteFavorite:input_type -> favorite.DeleteFavoriteReq
	10, // 6: favorite.FavoriteService.UpdateFavoriteFolderName:input_type -> favorite.UpdateFavoriteFolderNameReq
	12, // 7: favorite.FavoriteService.GetFavoriteFolders:input_type -> favorite.GetFavoriteFoldersReq
	14, // 8: favorite.FavoriteService.GetFavoritesByFolder:input_type -> favorite.GetFavoritesByFolderReq
	3,  // 9: favorite.FavoriteService.CreateFavoriteFolder:output_type -> favorite.CreateFavoriteFolderResp
	5,  // 10: favorite.FavoriteService.CreateFavorite:output_type -> favorite.CreateFavoriteResp
	7,  // 11: favorite.FavoriteService.DeleteFavoriteFolder:output_type -> favorite.DeleteFavoriteFolderResp
	9,  // 12: favorite.FavoriteService.DeleteFavorite:output_type -> favorite.DeleteFavoriteResp
	11, // 13: favorite.FavoriteService.UpdateFavoriteFolderName:output_type -> favorite.UpdateFavoriteFolderNameResp
	13, // 14: favorite.FavoriteService.GetFavoriteFolders:output_type -> favorite.GetFavoriteFoldersResp
	15, // 15: favorite.FavoriteService.GetFavoritesByFolder:output_type -> favorite.GetFavoritesByFolderResp
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_favorite_proto_init() }
func file_favorite_proto_init() {
	if File_favorite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_favorite_proto_rawDesc), len(file_favorite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favorite_proto_goTypes,
		DependencyIndexes: file_favorite_proto_depIdxs,
		MessageInfos:      file_favorite_proto_msgTypes,
	}.Build()
	File_favorite_proto = out.File
	file_favorite_proto_goTypes = nil
	file_favorite_proto_depIdxs = nil
}
