// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: follow.proto

package server

import (
	"context"

	"sea-try-go/service/follow/rpc/internal/logic"
	"sea-try-go/service/follow/rpc/internal/svc"
	"sea-try-go/service/follow/rpc/pb"
)

type FollowServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFollowServiceServer
}

func NewFollowServiceServer(svcCtx *svc.ServiceContext) *FollowServiceServer {
	return &FollowServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FollowServiceServer) Follow(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewFollowLogic(ctx, s.svcCtx)
	return l.Follow(in)
}

func (s *FollowServiceServer) Unfollow(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewUnfollowLogic(ctx, s.svcCtx)
	return l.Unfollow(in)
}

func (s *FollowServiceServer) Block(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewBlockLogic(ctx, s.svcCtx)
	return l.Block(in)
}

func (s *FollowServiceServer) Unblock(ctx context.Context, in *pb.RelationReq) (*pb.BaseResp, error) {
	l := logic.NewUnblockLogic(ctx, s.svcCtx)
	return l.Unblock(in)
}

func (s *FollowServiceServer) GetFollowList(ctx context.Context, in *pb.ListReq) (*pb.UserListResp, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

func (s *FollowServiceServer) GetBlockList(ctx context.Context, in *pb.ListReq) (*pb.UserListResp, error) {
	l := logic.NewGetBlockListLogic(ctx, s.svcCtx)
	return l.GetBlockList(in)
}

func (s *FollowServiceServer) GetFollowerList(ctx context.Context, in *pb.ListReq) (*pb.UserListResp, error) {
	l := logic.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}

func (s *FollowServiceServer) GetRecommendations(ctx context.Context, in *pb.ListReq) (*pb.RecommendResp, error) {
	l := logic.NewGetRecommendationsLogic(ctx, s.svcCtx)
	return l.GetRecommendations(in)
}
