// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	hot "sea-try-go/service/hot/api/internal/handler/hot"
	"sea-try-go/service/hot/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/articles",
				Handler: hot.GetHotArticlesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/hot/v1"),
	)
}
