// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	follow "sea-try-go/service/follow/api/internal/handler/follow"
	"sea-try-go/service/follow/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckBlacklistMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/block",
					Handler: follow.BlockHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/block/list",
					Handler: follow.GetBlockListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/follow",
					Handler: follow.FollowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/follow/list",
					Handler: follow.GetFollowListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/follower/list",
					Handler: follow.GetFollowerListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/recommendations",
					Handler: follow.GetRecommendationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unblock",
					Handler: follow.UnblockHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unfollow",
					Handler: follow.UnfollowHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/follow/v1"),
	)
}
