// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/follow.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationReq) Reset() {
	*x = RelationReq{}
	mi := &file_proto_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationReq) ProtoMessage() {}

func (x *RelationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationReq.ProtoReflect.Descriptor instead.
func (*RelationReq) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{0}
}

func (x *RelationReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RelationReq) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type BaseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	mi := &file_proto_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{1}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReq) Reset() {
	*x = ListReq{}
	mi := &file_proto_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReq) ProtoMessage() {}

func (x *ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReq.ProtoReflect.Descriptor instead.
func (*ListReq) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{2}
}

func (x *ListReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserIds       []int64                `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListResp) Reset() {
	*x = UserListResp{}
	mi := &file_proto_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListResp) ProtoMessage() {}

func (x *UserListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListResp.ProtoReflect.Descriptor instead.
func (*UserListResp) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{3}
}

func (x *UserListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UserListResp) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type RecommendResp struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          int32                          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Users         []*RecommendResp_RecommendUser `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResp) Reset() {
	*x = RecommendResp{}
	mi := &file_proto_follow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResp) ProtoMessage() {}

func (x *RecommendResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResp.ProtoReflect.Descriptor instead.
func (*RecommendResp) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{4}
}

func (x *RecommendResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RecommendResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RecommendResp) GetUsers() []*RecommendResp_RecommendUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type RecommendResp_RecommendUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MutualScore   int32                  `protobuf:"varint,2,opt,name=mutual_score,json=mutualScore,proto3" json:"mutual_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendResp_RecommendUser) Reset() {
	*x = RecommendResp_RecommendUser{}
	mi := &file_proto_follow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendResp_RecommendUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendResp_RecommendUser) ProtoMessage() {}

func (x *RecommendResp_RecommendUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendResp_RecommendUser.ProtoReflect.Descriptor instead.
func (*RecommendResp_RecommendUser) Descriptor() ([]byte, []int) {
	return file_proto_follow_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RecommendResp_RecommendUser) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *RecommendResp_RecommendUser) GetMutualScore() int32 {
	if x != nil {
		return x.MutualScore
	}
	return 0
}

var File_proto_follow_proto protoreflect.FileDescriptor

const file_proto_follow_proto_rawDesc = "" +
	"\n" +
	"\x12proto/follow.proto\x12\x06follow\"C\n" +
	"\vRelationReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\"0\n" +
	"\bBaseResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"P\n" +
	"\aListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"O\n" +
	"\fUserListResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x03R\auserIds\"\xc1\x01\n" +
	"\rRecommendResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x129\n" +
	"\x05users\x18\x03 \x03(\v2#.follow.RecommendResp.RecommendUserR\x05users\x1aO\n" +
	"\rRecommendUser\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12!\n" +
	"\fmutual_score\x18\x02 \x01(\x05R\vmutualScore2\xbc\x03\n" +
	"\rFollowService\x12/\n" +
	"\x06Follow\x12\x13.follow.RelationReq\x1a\x10.follow.BaseResp\x121\n" +
	"\bUnfollow\x12\x13.follow.RelationReq\x1a\x10.follow.BaseResp\x12.\n" +
	"\x05Block\x12\x13.follow.RelationReq\x1a\x10.follow.BaseResp\x120\n" +
	"\aUnblock\x12\x13.follow.RelationReq\x1a\x10.follow.BaseResp\x126\n" +
	"\rGetFollowList\x12\x0f.follow.ListReq\x1a\x14.follow.UserListResp\x125\n" +
	"\fGetBlockList\x12\x0f.follow.ListReq\x1a\x14.follow.UserListResp\x128\n" +
	"\x0fGetFollowerList\x12\x0f.follow.ListReq\x1a\x14.follow.UserListResp\x12<\n" +
	"\x12GetRecommendations\x12\x0f.follow.ListReq\x1a\x15.follow.RecommendRespB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_follow_proto_rawDescOnce sync.Once
	file_proto_follow_proto_rawDescData []byte
)

func file_proto_follow_proto_rawDescGZIP() []byte {
	file_proto_follow_proto_rawDescOnce.Do(func() {
		file_proto_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_follow_proto_rawDesc), len(file_proto_follow_proto_rawDesc)))
	})
	return file_proto_follow_proto_rawDescData
}

var file_proto_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_follow_proto_goTypes = []any{
	(*RelationReq)(nil),                 // 0: follow.RelationReq
	(*BaseResp)(nil),                    // 1: follow.BaseResp
	(*ListReq)(nil),                     // 2: follow.ListReq
	(*UserListResp)(nil),                // 3: follow.UserListResp
	(*RecommendResp)(nil),               // 4: follow.RecommendResp
	(*RecommendResp_RecommendUser)(nil), // 5: follow.RecommendResp.RecommendUser
}
var file_proto_follow_proto_depIdxs = []int32{
	5, // 0: follow.RecommendResp.users:type_name -> follow.RecommendResp.RecommendUser
	0, // 1: follow.FollowService.Follow:input_type -> follow.RelationReq
	0, // 2: follow.FollowService.Unfollow:input_type -> follow.RelationReq
	0, // 3: follow.FollowService.Block:input_type -> follow.RelationReq
	0, // 4: follow.FollowService.Unblock:input_type -> follow.RelationReq
	2, // 5: follow.FollowService.GetFollowList:input_type -> follow.ListReq
	2, // 6: follow.FollowService.GetBlockList:input_type -> follow.ListReq
	2, // 7: follow.FollowService.GetFollowerList:input_type -> follow.ListReq
	2, // 8: follow.FollowService.GetRecommendations:input_type -> follow.ListReq
	1, // 9: follow.FollowService.Follow:output_type -> follow.BaseResp
	1, // 10: follow.FollowService.Unfollow:output_type -> follow.BaseResp
	1, // 11: follow.FollowService.Block:output_type -> follow.BaseResp
	1, // 12: follow.FollowService.Unblock:output_type -> follow.BaseResp
	3, // 13: follow.FollowService.GetFollowList:output_type -> follow.UserListResp
	3, // 14: follow.FollowService.GetBlockList:output_type -> follow.UserListResp
	3, // 15: follow.FollowService.GetFollowerList:output_type -> follow.UserListResp
	4, // 16: follow.FollowService.GetRecommendations:output_type -> follow.RecommendResp
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_follow_proto_init() }
func file_proto_follow_proto_init() {
	if File_proto_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_follow_proto_rawDesc), len(file_proto_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_follow_proto_goTypes,
		DependencyIndexes: file_proto_follow_proto_depIdxs,
		MessageInfos:      file_proto_follow_proto_msgTypes,
	}.Build()
	File_proto_follow_proto = out.File
	file_proto_follow_proto_goTypes = nil
	file_proto_follow_proto_depIdxs = nil
}
