// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: follow.proto

package followservice

import (
	"context"

	"sea-try-go/service/follow/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp                    = pb.BaseResp
	ListReq                     = pb.ListReq
	RecommendResp               = pb.RecommendResp
	RecommendResp_RecommendUser = pb.RecommendResp_RecommendUser
	RelationReq                 = pb.RelationReq
	UserListResp                = pb.UserListResp

	FollowService interface {
		Follow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		Unfollow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		Block(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		Unblock(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetFollowList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		GetBlockList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		GetFollowerList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error)
		GetRecommendations(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*RecommendResp, error)
	}

	defaultFollowService struct {
		cli zrpc.Client
	}
)

func NewFollowService(cli zrpc.Client) FollowService {
	return &defaultFollowService{
		cli: cli,
	}
}

func (m *defaultFollowService) Follow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Follow(ctx, in, opts...)
}

func (m *defaultFollowService) Unfollow(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Unfollow(ctx, in, opts...)
}

func (m *defaultFollowService) Block(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Block(ctx, in, opts...)
}

func (m *defaultFollowService) Unblock(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.Unblock(ctx, in, opts...)
}

func (m *defaultFollowService) GetFollowList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetFollowList(ctx, in, opts...)
}

func (m *defaultFollowService) GetBlockList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetBlockList(ctx, in, opts...)
}

func (m *defaultFollowService) GetFollowerList(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetFollowerList(ctx, in, opts...)
}

func (m *defaultFollowService) GetRecommendations(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*RecommendResp, error) {
	client := pb.NewFollowServiceClient(m.cli.Conn())
	return client.GetRecommendations(ctx, in, opts...)
}
