// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	knowledge "sea-try-go/service/knowledge/api/internal/handler/knowledge"
	product "sea-try-go/service/knowledge/api/internal/handler/product"
	worker "sea-try-go/service/knowledge/api/internal/handler/worker"
	"sea-try-go/service/knowledge/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/modules",
				Handler: knowledge.ListModulesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/modules/:module_id",
				Handler: knowledge.GetModuleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/modules/:module_id/published",
				Handler: knowledge.GetPublishedReleaseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/modules/:module_id/published-releases/:release_id",
				Handler: knowledge.GetHistoricalReleaseHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/modules/:module_id/releases/:release_id/revisions",
				Handler: knowledge.ListPublishedRevisionsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/modules/:module_id/releases/:release_id/revisions/:revision_id",
				Handler: knowledge.GetPublishedRevisionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/knowledge"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Administrator},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/builds/:build_id/cancel",
					Handler: knowledge.CancelBuildHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/compiles/:compile_id/cancel",
					Handler: knowledge.CancelCompileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules",
					Handler: knowledge.CreateModuleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/modules/:module_id/activation",
					Handler: knowledge.ActivateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/builds",
					Handler: knowledge.ListBuildsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/builds/:build_id",
					Handler: knowledge.GetModuleBuildHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/compiles",
					Handler: knowledge.ListCompilesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/compiles",
					Handler: knowledge.CreateCompileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/compiles/:compile_id",
					Handler: knowledge.GetModuleCompileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/releases",
					Handler: knowledge.ListReleasesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/releases",
					Handler: knowledge.CreateReleaseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/releases/:release_id",
					Handler: knowledge.GetModuleReleaseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/releases/current",
					Handler: knowledge.CurrentReleaseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/revisions",
					Handler: knowledge.ListRevisionsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/revisions/:revision_id",
					Handler: knowledge.GetModuleRevisionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/search-judgments",
					Handler: knowledge.RecordSearchJudgmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/search-judgments/withdrawals",
					Handler: knowledge.WithdrawSearchJudgmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/sources",
					Handler: knowledge.CreateSourceHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/wiki-pages/:page_id/revisions",
					Handler: knowledge.CreateWikiHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/modules/:module_id/withdrawals",
					Handler: knowledge.WithdrawHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/releases/:release_id/index-builds",
					Handler: knowledge.CreateBuildHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/workbench/modules",
					Handler: knowledge.ListDraftModulesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/workbench/modules/:module_id",
					Handler: knowledge.GetDraftModuleHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1/knowledge"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/answer-sessions/:session_id/accepted-answers",
				Handler: product.ListProductAcceptedAnswersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answer-sessions/:session_id/accepted-answers/:answer_id",
				Handler: product.GetProductAcceptedAnswerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answer-sessions/:session_id/accepted-answers/:answer_id/citations",
				Handler: product.GetProductAnswerCitationStatesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/answer-sessions/:session_id/searches",
				Handler: product.CreateProductSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answer-sessions/:session_id/searches/:search_id",
				Handler: product.GetProductSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/answer-sessions/:session_id/tool-runs",
				Handler: product.CreateToolParentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answer-sessions/:session_id/tool-runs/:operation_id",
				Handler: product.GetToolParentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/answer-sessions/:session_id/tool-runs/:operation_id/evidence-reads",
				Handler: product.ReadToolEvidenceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/answer-sessions/:session_id/tool-runs/:operation_id/searches",
				Handler: product.CreateToolSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/answer-sessions/:session_id/tool-runs/:operation_id/searches/:search_id",
				Handler: product.GetToolSearchHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.UserAuth.AccessSecret),
		rest.WithPrefix("/v1/knowledge"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Worker},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/accepted-answers",
					Handler: worker.CommitAcceptedAnswerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/accepted-answers",
					Handler: worker.ListAcceptedAnswersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/accepted-answers/:answer_id",
					Handler: worker.GetAcceptedAnswerHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/builds/:build_id",
					Handler: worker.GetBuildHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/builds/:build_id/claim",
					Handler: worker.ClaimBuildHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/builds/:build_id/results",
					Handler: worker.AcceptBuildHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/compiles/:compile_id",
					Handler: worker.GetCompileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/compiles/:compile_id/claim",
					Handler: worker.ClaimCompileHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/compiles/:compile_id/results",
					Handler: worker.AcceptCompileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/modules/:module_id/search-snapshot",
					Handler: worker.GetCurrentSearchSnapshotHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/releases/:release_id",
					Handler: worker.GetReleaseHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/revisions/:revision_id",
					Handler: worker.GetRevisionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/search-citations",
					Handler: worker.AcceptSearchCitationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search-citations/:search_id",
					Handler: worker.GetSearchCitationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search-judgments/events/:event_id",
					Handler: worker.GetSearchJudgmentEventHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/search-sources/read",
					Handler: worker.ReadSearchSourceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/internal/v1/knowledge"),
	)
}
