// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	article "sea-try-go/service/article/api/internal/handler/article"
	"sea-try-go/service/article/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

const uploadImageMaxBytes int64 = 10 * 1024 * 1024

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/article",
				Handler: article.CreateArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/article/:id",
				Handler: article.UpdateArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/article/:id",
				Handler: article.DeleteArticleHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
		rest.WithTimeout(70*time.Second),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/article/:id",
				Handler: article.GetArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/articles",
				Handler: article.ListArticlesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload",
				Handler: article.UploadImageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(uploadImageMaxBytes),
	)
}
