// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateFavoriteFolderReq struct {
	Name string `json:"name"`
}

type CreateFavoriteFolderResp struct {
	FolderId int64 `json:"folderId,string"`
}

type CreateFavoriteReq struct {
	FolderId   int64  `json:"folderId,string"`
	TargetId   string `json:"targetId"`
	TargetType string `json:"targetType"`
	Title      string `json:"title,optional"`
	Cover      string `json:"cover,optional"`
}

type CreateFavoriteResp struct {
	FavoriteId int64 `json:"favoriteId,string"`
}

type DeleteFavoriteFolderReq struct {
	FolderId int64 `json:"folderId,string"`
}

type DeleteFavoriteFolderResp struct {
	Success bool `json:"success"`
}

type DeleteFavoriteReq struct {
	FavoriteId int64 `json:"favoriteId,string"`
}

type DeleteFavoriteResp struct {
	Success bool `json:"success"`
}

type FavoriteFolder struct {
	FolderId  int64  `json:"folderId,string"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type FavoriteItem struct {
	FavoriteId int64  `json:"favoriteId,string"`
	FolderId   int64  `json:"folderId,string"`
	TargetId   string `json:"targetId"`
	TargetType string `json:"targetType"`
	Title      string `json:"title,optional"`
	Cover      string `json:"cover,optional"`
	CreatedAt  int64  `json:"createdAt"`
}

type GetFavoriteFoldersReq struct {
}

type GetFavoriteFoldersResp struct {
	Folders []FavoriteFolder `json:"folders"`
}

type GetFavoritesByFolderReq struct {
	FolderId int64 `form:"folderId,string"`
}

type GetFavoritesByFolderResp struct {
	Favorites []FavoriteItem `json:"favorites"`
}

type UpdateFavoriteFolderNameReq struct {
	FolderId int64  `json:"folderId,string"`
	Name     string `json:"name"`
}

type UpdateFavoriteFolderNameResp struct {
	Success bool `json:"success"`
}
