// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FollowListReq struct {
	UserId int64 `json:"user_id,string,optional"`
	Offset int32 `json:"offset,optional"`
	Limit  int32 `json:"limit,optional"`
}

type FollowUserListResp struct {
	UserIds []int64 `json:"user_ids"`
}

type RecommendListResp struct {
	Users []RecommendUser `json:"users"`
}

type RecommendUser struct {
	TargetId    int64 `json:"target_id,string"`
	MutualScore int32 `json:"mutual_score"`
}

type RelationActionReq struct {
	TargetId int64 `json:"target_id,string"`
}

type RelationActionResp struct {
	Success bool `json:"success"`
}
