// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AcceptBuildReq struct {
	BuildId           string `path:"build_id"`
	Generation        int64  `json:"generation"`
	AttemptId         string `json:"attempt_id"`
	LeaseEpoch        int64  `json:"lease_epoch"`
	CancelVersion     int64  `json:"cancel_version"`
	ManifestHash      string `json:"manifest_hash"`
	IndexManifestRef  string `json:"index_manifest_ref,optional"`
	IndexManifestHash string `json:"index_manifest_hash,optional"`
	State             string `json:"state"`
	ErrorCode         string `json:"error_code,optional"`
}

type AcceptCompileReq struct {
	State         string      `json:"state,optional"`
	ErrorCode     string      `json:"error_code,optional"`
	CompileId     string      `path:"compile_id"`
	Generation    int64       `json:"generation"`
	AttemptId     string      `json:"attempt_id"`
	LeaseEpoch    int64       `json:"lease_epoch"`
	CancelVersion int64       `json:"cancel_version"`
	InputHash     string      `json:"input_hash"`
	ObjectKey     string      `json:"object_key,optional"`
	ContentHash   string      `json:"content_hash,optional"`
	Title         string      `json:"title,optional"`
	SourceRefs    []SourceRef `json:"source_refs,optional"`
}

type ActivateReq struct {
	ModuleId                string `path:"module_id"`
	ReleaseId               string `json:"release_id"`
	BuildId                 string `json:"build_id"`
	ExpectedPointerRevision int64  `json:"expected_pointer_revision"`
	Reason                  string `json:"reason"`
	IdempotencyKey          string `json:"idempotency_key,optional"`
}

type Build struct {
	LeaseExpiresAt    string `json:"lease_expires_at"`
	BuildId           string `json:"build_id"`
	ReleaseId         string `json:"release_id"`
	ModuleId          string `json:"module_id"`
	ManifestHash      string `json:"manifest_hash"`
	Generation        int64  `json:"generation"`
	State             string `json:"state"`
	AttemptId         string `json:"attempt_id"`
	LeaseEpoch        int64  `json:"lease_epoch"`
	CancelVersion     int64  `json:"cancel_version"`
	IndexManifestRef  string `json:"index_manifest_ref"`
	IndexManifestHash string `json:"index_manifest_hash"`
	ErrorCode         string `json:"error_code"`
}

type BuildEnvelope struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data Build  `json:"data"`
}

type BuildPath struct {
	BuildId string `path:"build_id"`
}

type CancelBuildReq struct {
	BuildId        string `path:"build_id"`
	Reason         string `json:"reason"`
	IdempotencyKey string `json:"idempotency_key"`
}

type CancelCompileReq struct {
	CompileId      string `path:"compile_id"`
	Reason         string `json:"reason"`
	IdempotencyKey string `json:"idempotency_key"`
}

type ClaimBuildReq struct {
	LeaseExpiresAt string `json:"lease_expires_at"`
	BuildId        string `path:"build_id"`
	Generation     int64  `json:"generation"`
	AttemptId      string `json:"attempt_id"`
	LeaseEpoch     int64  `json:"lease_epoch"`
	CancelVersion  int64  `json:"cancel_version"`
	ManifestHash   string `json:"manifest_hash"`
}

type ClaimCompileReq struct {
	LeaseExpiresAt string `json:"lease_expires_at"`
	CompileId      string `path:"compile_id"`
	Generation     int64  `json:"generation"`
	AttemptId      string `json:"attempt_id"`
	LeaseEpoch     int64  `json:"lease_epoch"`
	CancelVersion  int64  `json:"cancel_version"`
	InputHash      string `json:"input_hash"`
}

type Compile struct {
	ErrorCode         string   `json:"error_code"`
	LeaseExpiresAt    string   `json:"lease_expires_at"`
	CompileId         string   `json:"compile_id"`
	ModuleId          string   `json:"module_id"`
	PageId            string   `json:"page_id"`
	BaseRevisionId    string   `json:"base_revision_id"`
	SourceRevisionIds []string `json:"source_revision_ids"`
	Guidance          string   `json:"guidance"`
	InputHash         string   `json:"input_hash"`
	State             string   `json:"state"`
	Generation        int64    `json:"generation"`
	AttemptId         string   `json:"attempt_id"`
	LeaseEpoch        int64    `json:"lease_epoch"`
	CancelVersion     int64    `json:"cancel_version"`
	RevisionId        string   `json:"revision_id"`
	ResultHash        string   `json:"result_hash"`
}

type CompileEnvelope struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data Compile `json:"data"`
}

type CompilePath struct {
	CompileId string `path:"compile_id"`
}

type CreateBuildReq struct {
	ReleaseId      string `path:"release_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

type CreateCompileReq struct {
	ModuleId          string   `path:"module_id"`
	PageId            string   `json:"page_id"`
	BaseRevisionId    string   `json:"base_revision_id,optional"`
	SourceRevisionIds []string `json:"source_revision_ids"`
	Guidance          string   `json:"guidance"`
	IdempotencyKey    string   `json:"idempotency_key"`
}

type CreateModuleReq struct {
	Title          string `json:"title"`
	Description    string `json:"description,optional"`
	Category       string `json:"category,optional"`
	IdempotencyKey string `json:"idempotency_key"`
}

type CreateReleaseReq struct {
	ModuleId          string             `path:"module_id"`
	SourceRevisionIds []string           `json:"source_revision_ids"`
	WikiRevisionIds   []string           `json:"wiki_revision_ids"`
	ChunkingProfile   string             `json:"chunking_profile"`
	RetrievalProfiles []RetrievalProfile `json:"retrieval_profiles"`
	IdempotencyKey    string             `json:"idempotency_key"`
}

type CreateSourceReq struct {
	ModuleId       string `path:"module_id"`
	EntityId       string `json:"source_id,optional"`
	BaseRevisionId string `json:"base_revision_id,optional"`
	Title          string `json:"title"`
	Content        string `json:"content"`
	MediaType      string `json:"media_type"`
	Provenance     string `json:"provenance"`
	IdempotencyKey string `json:"idempotency_key"`
}

type CreateWikiReq struct {
	ModuleId       string      `path:"module_id"`
	PageId         string      `path:"page_id"`
	BaseRevisionId string      `json:"base_revision_id,optional"`
	Title          string      `json:"title"`
	Content        string      `json:"content"`
	SourceRefs     []SourceRef `json:"source_refs"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type ListBuildsResp struct {
	Items      []Build `json:"items"`
	NextCursor string  `json:"next_cursor,optional,omitempty"`
}

type ListBuildsRespEnvelope struct {
	Code int            `json:"code"`
	Msg  string         `json:"msg"`
	Data ListBuildsResp `json:"data"`
}

type ListCompilesResp struct {
	Items      []Compile `json:"items"`
	NextCursor string    `json:"next_cursor,optional,omitempty"`
}

type ListCompilesRespEnvelope struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data ListCompilesResp `json:"data"`
}

type ListModulesReq struct {
	Limit  int    `form:"limit,optional,default=12"`
	Cursor string `form:"cursor,optional"`
}

type ListModulesResp struct {
	Items      []Module `json:"items"`
	NextCursor string   `json:"next_cursor,optional,omitempty"`
}

type ListModulesRespEnvelope struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data ListModulesResp `json:"data"`
}

type ListReleasesResp struct {
	Items      []Release `json:"items"`
	NextCursor string    `json:"next_cursor,optional,omitempty"`
}

type ListReleasesRespEnvelope struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data ListReleasesResp `json:"data"`
}

type ListRevisionsResp struct {
	Items      []Revision `json:"items"`
	NextCursor string     `json:"next_cursor,optional,omitempty"`
}

type ListRevisionsRespEnvelope struct {
	Code int               `json:"code"`
	Msg  string            `json:"msg"`
	Data ListRevisionsResp `json:"data"`
}

type Module struct {
	Id              string `json:"id"`
	Title           string `json:"title"`
	Subtitle        string `json:"subtitle"`
	Description     string `json:"description"`
	Category        string `json:"category"`
	Image           string `json:"image"`
	Sources         int    `json:"sources"`
	Pages           int    `json:"pages"`
	Release         string `json:"release"`
	Updated         string `json:"updated"`
	Lifecycle       string `json:"lifecycle"`
	PointerRevision int64  `json:"pointer_revision"`
	ActiveReleaseId string `json:"active_release_id"`
	ActiveBuildId   string `json:"active_build_id"`
}

type ModuleBuildPath struct {
	ModuleId string `path:"module_id"`
	BuildId  string `path:"build_id"`
}

type ModuleCompilePath struct {
	ModuleId  string `path:"module_id"`
	CompileId string `path:"compile_id"`
}

type ModuleEnvelope struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data Module `json:"data"`
}

type ModulePageReq struct {
	ModuleId string `path:"module_id"`
	Limit    int    `form:"limit,optional,default=20"`
	Cursor   string `form:"cursor,optional"`
}

type ModulePath struct {
	ModuleId string `path:"module_id"`
}

type ModuleReleasePath struct {
	ModuleId  string `path:"module_id"`
	ReleaseId string `path:"release_id"`
}

type ModuleRevisionPath struct {
	ModuleId   string `path:"module_id"`
	RevisionId string `path:"revision_id"`
}

type PublishedRevisionPath struct {
	ModuleId   string `path:"module_id"`
	ReleaseId  string `path:"release_id"`
	RevisionId string `path:"revision_id"`
}

type PublishedRevisionsReq struct {
	ModuleId  string `path:"module_id"`
	ReleaseId string `path:"release_id"`
	Limit     int    `form:"limit,optional,default=20"`
	Cursor    string `form:"cursor,optional"`
}

type Receipt struct {
	Accepted bool `json:"accepted"`
}

type ReceiptEnvelope struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data Receipt `json:"data"`
}

type Release struct {
	ReleaseId         string             `json:"release_id"`
	ModuleId          string             `json:"module_id"`
	Ordinal           int64              `json:"ordinal"`
	SourceRevisionIds []string           `json:"source_revision_ids"`
	WikiRevisionIds   []string           `json:"wiki_revision_ids"`
	ChunkingProfile   string             `json:"chunking_profile"`
	RetrievalProfiles []RetrievalProfile `json:"retrieval_profiles"`
	ManifestHash      string             `json:"manifest_hash"`
	ManifestRef       string             `json:"manifest_ref"`
	CreatedAt         string             `json:"created_at"`
}

type ReleaseEnvelope struct {
	Code int     `json:"code"`
	Msg  string  `json:"msg"`
	Data Release `json:"data"`
}

type ReleasePath struct {
	ReleaseId string `path:"release_id"`
}

type ReleaseState struct {
	ActiveReleaseId    string `json:"active_release_id"`
	ActiveBuildId      string `json:"active_build_id"`
	PointerRevision    int64  `json:"pointer_revision"`
	CandidateReleaseId string `json:"candidate_release_id"`
	BuildId            string `json:"build_id"`
	BuildState         string `json:"build_state"`
	ManifestHash       string `json:"manifest_hash"`
}

type ReleaseStateEnvelope struct {
	Code int          `json:"code"`
	Msg  string       `json:"msg"`
	Data ReleaseState `json:"data"`
}

type RetrievalProfile struct {
	Lane        string `json:"lane"`
	Encoder     string `json:"encoder"`
	Tokenizer   string `json:"tokenizer"`
	Space       string `json:"space"`
	Dimensions  int    `json:"dimensions"`
	Mask        string `json:"mask,optional"`
	Aggregation string `json:"aggregation,optional"`
}

type Revision struct {
	RevisionId     string      `json:"revision_id"`
	ModuleId       string      `json:"module_id"`
	EntityId       string      `json:"entity_id"`
	Kind           string      `json:"kind"`
	BaseRevisionId string      `json:"base_revision_id"`
	Title          string      `json:"title"`
	MediaType      string      `json:"media_type"`
	ObjectKey      string      `json:"object_key"`
	ContentHash    string      `json:"content_hash"`
	Content        string      `json:"content,optional,omitempty"`
	SourceRefs     []SourceRef `json:"source_refs"`
	Provenance     string      `json:"provenance"`
	CreatedBy      string      `json:"created_by"`
	CreatedAt      string      `json:"created_at"`
	Withdrawn      bool        `json:"withdrawn"`
}

type RevisionEnvelope struct {
	Code int      `json:"code"`
	Msg  string   `json:"msg"`
	Data Revision `json:"data"`
}

type RevisionPath struct {
	RevisionId string `path:"revision_id"`
}

type SourceRef struct {
	RevisionId string `json:"revision_id"`
	Locator    string `json:"locator"`
}

type WithdrawReq struct {
	ModuleId       string `path:"module_id"`
	TargetKind     string `json:"target_kind"`
	TargetId       string `json:"target_id"`
	Reason         string `json:"reason"`
	IdempotencyKey string `json:"idempotency_key"`
}
